modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="http://www.minecraftforge.net/"
logoFile="forge_logo.png"

[[mods]]
    modId="forge"
    # We use the global forge version
    version="${global.forgeVersion}"
    updateJSONURL="https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json"
    displayName="Forge"
    credits="LexManos,cpw,Mezz,fry,tterrag,gigaherz,illy"
    authors="LexManos,cpw,Mezz,fry,Spacetoad,Eloraam"
    description='''
    Forge, a broad compatibility API.
    '''

[[mods]]
     modId="mohist"
     version="${file.jarVersion}"
     displayName="Mohist"
     authors="Mohist DEV team"
     description='''
     This is a Forge + Bukkit port server mod
     '''

    