modLoader="javafml"
loaderVersion="[24,]"

[[mods]]
    modId="arclight"
    version="${version}"
    displayName="Arclight Mod"
    credits="IzzelAliz,lona"
    authors="IzzelAliz,lona"
    description='''
    Arclight bukkit layer for MinecraftForge
    '''
